# Generated by Django 5.0.4 on 2024-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name="Ссылка на видео"),
        ),
    ]
